[package]
name = "rust-deep-learning"
version = "0.1.0"
authors = ["kitagawa <kitadrum50@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotlib = "0.4.0"
